apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: bazarr
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/bazarr
  values:
    route:
      main:
        enabled: true
        hostnames: [prowlarr.o5s.lol]
        parentRefs:
          - name: traefik-gateway
            namespace: network
