apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: charts/jellyfin
      interval: 12h
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: jellyfin
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/jellyfin/jellyfin-helm/tree/master/charts/jellyfin
