apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: radarr
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/radarr
  values:
    metrics:
      main:
        enabled: false
    route:
      main:
        enabled: true
        hostnames: [radarr.o5s.lol]
        parentRefs:
          - name: traefik-gateway
            namespace: network
