apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: sonarr
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: 23.x
  interval: 1h
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/sonarr
