apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: security
spec:
  interval: 24h
  url: https://charts.jetstack.io

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: security
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: 1.x
  interval: 1h
  # @ref https://artifacthub.io/packages/helm/cert-manager/cert-manager
  values:
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
    crds:
      enabled: true
