apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: network
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/traefik/helm

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  chart:
    spec:
      chart: traefik
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 33.x
  interval: 1h
  # @ref https://artifacthub.io/packages/helm/traefik/traefik
  values:
    gateway:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      listeners:
        websecure-root:
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: o5s-lol-ca
          hostname: o5s.lol
          mode: Terminate
          namespacePolicy: All
        websecure:
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: o5s-lol-ca
          hostname: "*.o5s.lol"
          mode: Terminate
          namespacePolicy: All
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: [websecure]
        matchRule: Host(`o5s.lol`)
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    tlsStore:
      default:
        defaultCertificate:
          secretName: o5s-lol-ca
