apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: network
  hostnames: [flix.o5s.lol]
  rules:
    - matches:
      - path:
          value: /
      backendRefs:
        - name: jellyfin
          port: 8096
