apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia.yaml
  - bazarr.yaml
  - headlamp.yaml
  - homepage.yaml
  - jellyfin.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - weave-gitops.yaml
