apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 24h
  url: https://charts.authelia.com

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  chart:
    spec:
      chart: authelia
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: authelia
      version: 0.x
  interval: 1h
  # @ref https://github.com/authelia/chartrepo/tree/master/charts/authelia
  values:
    configMap:
      authentication_backend:
        file:
          enabled: true
      notifier:
        filesystem:
          enabled: true
      session:
        cookies:
          - domain: o5s.lol
            subdomain: auth
      storage:
        postgres:
          enabled: true
