apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  chart:
    spec:
      chart: headlamp
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/headlamp-k8s/headlamp/tree/main/charts/headlamp

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     kubernetes.io/service-account.name: headlamp-admin
#   name: headlamp-admin-token
#   namespace: headlamp
# type: kubernetes.io/service-account-token
