apiVersion: v1
kind: Namespace
metadata:
  name: headlamp

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/component: ui
  name: headlamp
  namespace: headlamp
spec:
  interval: 24h
  url: https://headlamp-k8s.github.io/headlamp

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  chart:
    spec:
      chart: headlamp
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp
  interval: 1h
  # @ref https://github.com/headlamp-k8s/headlamp/tree/main/charts/headlamp

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     kubernetes.io/service-account.name: headlamp-admin
#   name: headlamp-admin-token
#   namespace: headlamp
# type: kubernetes.io/service-account-token
