apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chart:
    spec:
      chart: homepage
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/jameswynn/helm-charts/tree/main/charts/homepage
