apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
spec:
  interval: 24h
  url: https://charts.authelia.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/component: ui
  name: headlamp
spec:
  interval: 24h
  url: https://headlamp-k8s.github.io/headlamp
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jameswynn
spec:
  interval: 24h
  url: http://jameswynn.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jellyfin
spec:
  interval: 24h
  url: https://github.com/jellyfin/jellyfin-helm
  ref:
    tag: 1.3.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/traefik/helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: truecharts
spec:
  interval: 24h
  type: oci
  url: oci://tccr.io/truecharts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: weave-gitops
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
